/**
 * Static reference data for each US state's real estate investment (tax lien/deed) landscape.
 * Sourced from state statutes and industry references. Update as laws change.
 */

export type InvestmentCategory =
  | 'TAX_LIEN'
  | 'TAX_DEED'
  | 'REDEEMABLE_DEED'
  | 'HYBRID'
  | 'NOT_ACTIVE'

export type StateInfo = {
  state: string           // 2-letter abbreviation
  stateName: string
  investmentType: InvestmentCategory
  investmentLabel: string // Human-readable
  interestRate: string | null
  bidMethod: string | null
  redemptionPeriod: string | null
  saleDates: string | null
  overTheCounter: boolean
  stateWebsite: string | null
  stateStatutes: string | null
  summary: string | null  // 1-2 sentence overview
}

export const STATE_INFO: Record<string, StateInfo> = {
  AL: {
    state: 'AL', stateName: 'Alabama',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '12%', bidMethod: 'Bid Down Interest',
    redemptionPeriod: '3 Years', saleDates: 'May',
    overTheCounter: true,
    stateWebsite: 'http://www.alabama.gov/',
    stateStatutes: 'http://revenue.alabama.gov/advalorem/rulesandregs/code/landlaw.PDF',
    summary: 'Tax liens purchased with a 3-year redemption period at 12% annual return (1% per month). Investors bid down the interest rate, starting at 12%. Some counties also offer tax deed properties.',
  },
  AK: {
    state: 'AK', stateName: 'Alaska',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Varies by Municipality',
    redemptionPeriod: '1 Year (Minimum)', saleDates: 'Varies by Municipality',
    overTheCounter: false,
    stateWebsite: 'http://alaska.gov/',
    stateStatutes: 'http://www.legis.state.ak.us/basis/statutes.asp',
    summary: 'Alaska handles tax sales through boroughs rather than counties. Sales may be called tax deed sales, land sales, or tax foreclosure sales depending on the borough. Premium bid and sealed bid methods are most common.',
  },
  AZ: {
    state: 'AZ', stateName: 'Arizona',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '16%', bidMethod: 'Bid Down Interest Rate',
    redemptionPeriod: '3 Years', saleDates: 'February',
    overTheCounter: true,
    stateWebsite: 'http://www.az.gov/',
    stateStatutes: 'http://www.azleg.state.az.us/ArizonaRevisedStatutes.asp?Title=42',
    summary: 'Arizona holds annual tax lien auctions in February with a 16% maximum interest rate bid down by investors. Property owners have 3 years to redeem; after which the lien holder may foreclose via the superior court.',
  },
  AR: {
    state: 'AR', stateName: 'Arkansas',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: '30 Days (Post-Sale)', saleDates: 'Year Round',
    overTheCounter: true,
    stateWebsite: 'http://www.arkansas.gov/',
    stateStatutes: 'https://www.salinecollector.ar.gov/tax-info/statutes',
    summary: 'Tax deed state. Starting bid is typically 20-30% of actual property value. Previous owners have 30 days post-sale to redeem; investors receive full refund if redeemed. Sealed bids may be mailed to the commissioner of state lands.',
  },
  CA: {
    state: 'CA', stateName: 'California',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Spring',
    overTheCounter: false,
    stateWebsite: 'http://www.ca.gov/',
    stateStatutes: 'http://www.leginfo.ca.gov/cgi-bin/calawquery?codesection=rtc&codebody=&hits=20',
    summary: 'California sells tax deeds via oral auction (and online via bid4assets.com for many large counties). Registration required, often 2+ weeks in advance with a required deposit. Property owner privacy laws (CA GC6254.21) may restrict owner name lookups.',
  },
  CO: {
    state: 'CO', stateName: 'Colorado',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '9% above federal discount rate', bidMethod: 'Premium',
    redemptionPeriod: '3 Years', saleDates: 'October – December',
    overTheCounter: true,
    stateWebsite: 'https://www.colorado.gov/',
    stateStatutes: null,
    summary: 'Colorado tax lien certificates carry a 3-year redemption period with interest at 9% above the federal discount rate. As of July 1, 2024, tax deeds are no longer automatically issued to lien holders — a second public auction is held to determine the new owner.',
  },
  CT: {
    state: 'CT', stateName: 'Connecticut',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien (Hybrid Deed)',
    interestRate: '18%', bidMethod: 'Premium',
    redemptionPeriod: '1 Year', saleDates: 'Varies',
    overTheCounter: false,
    stateWebsite: 'http://portal.ct.gov/',
    stateStatutes: 'https://www.cga.ct.gov/2014/sup/title_12.htm',
    summary: 'Connecticut sells hybrid tax deeds with a 1-year redemption period at 18% annual return. The deed is held unrecorded by the investor for 12 months. If not redeemed, all redemption rights terminate and the investor takes possession.',
  },
  DC: {
    state: 'DC', stateName: 'Washington D.C.',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '18%', bidMethod: 'Premium',
    redemptionPeriod: '6 Months', saleDates: 'July',
    overTheCounter: true,
    stateWebsite: 'http://dc.gov/',
    stateStatutes: 'http://dccode.elaws.us/gateway/codepdf/title42/chapter42-11/1753-01-01/chapter42-11(1753-01-01).pdf',
    summary: 'D.C. holds an annual tax lien auction in July. Unsold liens go into an ongoing discount auction. 6-month redemption period at 18% annual interest.',
  },
  DE: {
    state: 'DE', stateName: 'Delaware',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Hybrid Tax Deed',
    interestRate: '15% Penalty', bidMethod: 'Premium',
    redemptionPeriod: '60 Days', saleDates: 'Year Round',
    overTheCounter: false,
    stateWebsite: 'http://delaware.gov/',
    stateStatutes: 'http://delcode.delaware.gov/title9/c087/index.shtml',
    summary: 'Delaware has 3 counties with tax deed sales conducted by the county sheriff. 60-day redemption period with 15% penalty. The county attorney must petition the Supreme Court to complete the sale after purchase.',
  },
  FL: {
    state: 'FL', stateName: 'Florida',
    investmentType: 'HYBRID', investmentLabel: 'Tax Lien + Tax Deed',
    interestRate: '18% (5% minimum guaranteed)', bidMethod: 'Bid Down Interest Rate',
    redemptionPeriod: '2 Years', saleDates: 'May (Liens) · Year Round (Deeds)',
    overTheCounter: true,
    stateWebsite: 'http://www.myflorida.com/',
    stateStatutes: 'http://www.leg.state.fl.us/Statutes/index.cfm?mode=View%20Statutes&SubMenu=1&App_mode=Display_Statute&Search_String=Title+14+Chapter+197&URL=0100-0199/0197/Sections/0197.502.html',
    summary: 'Florida is a hybrid state: all 67 counties hold annual tax lien sales (May) plus frequent tax deed sales once the 2-year redemption expires. Investors bid down from 18% with a guaranteed 5% minimum return on early redemptions. Tax collector oversees liens; clerk of courts oversees deeds.',
  },
  GA: {
    state: 'GA', stateName: 'Georgia',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Redeemable Deed',
    interestRate: '20% (year 1), 10% (subsequent years)', bidMethod: 'Premium',
    redemptionPeriod: '1 Year', saleDates: 'Varies by County',
    overTheCounter: false,
    stateWebsite: 'http://www.georgia.gov/',
    stateStatutes: 'http://dor.georgia.gov/liens',
    summary: 'Georgia tax deeds carry a 1-year redemption period with a 20% penalty for year 1 and 10% each additional year. Investor must send certified letters and run a newspaper foreclosure notice for 4 weeks to terminate redemption rights after expiration.',
  },
  HI: {
    state: 'HI', stateName: 'Hawaii',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Redeemable Deed',
    interestRate: '12% Penalty', bidMethod: 'Premium',
    redemptionPeriod: '1 Year', saleDates: 'Varies (June, Nov, Dec)',
    overTheCounter: false,
    stateWebsite: 'http://www.ehawaii.gov/',
    stateStatutes: 'http://www.honolulu.gov/rep',
    summary: 'Hawaii sells hybrid tax deeds with a 1-year redemption period and 12% penalty. Tax deeds must be recorded within 60 days of the sale to lock in the 12-month redemption window; late recording restarts the clock from the recording date.',
  },
  ID: {
    state: 'ID', stateName: 'Idaho',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Summer',
    overTheCounter: true,
    stateWebsite: 'http://www.idaho.gov/',
    stateStatutes: 'http://legislature.idaho.gov/idstat/TOC/IDStatutesTOC.htm',
    summary: 'Idaho tax deeds are sold via oral premium bid auction. County commissioners set the minimum bid. Board of county commissioners reserves the right to reject any bid. Most liens on the property are extinguished through the sale.',
  },
  IL: {
    state: 'IL', stateName: 'Illinois',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '18%', bidMethod: 'Bid Down Interest Rate',
    redemptionPeriod: '2 – 3 Years', saleDates: 'Varies by County',
    overTheCounter: true,
    stateWebsite: 'http://www.illinois.gov/Pages/default.aspx',
    stateStatutes: 'http://www.ilga.gov/legislation/ilcs/ilcs4.asp?DocName=003502000HTit%2E+7&ActID=596&ChapAct=35%26nbsp%3BILCS%26nbsp%3B200%2F&ChapterID=8&ChapterName=REVENUE&SectionID=9263&SeqStart=56900000&SeqEnd=77300000&ActName=Property+Tax+Code%2E',
    summary: 'Illinois holds Regular Tax Sales (properties delinquent 1 year, 18% max bidding down) and Scavenger Sales (2+ years delinquent, $250 minimum bid). Standard redemption is 2 years, extendable to 3. Tax deed must be recorded within 1 year of redemption expiration.',
  },
  IN: {
    state: 'IN', stateName: 'Indiana',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '10-15% Penalty', bidMethod: 'Premium',
    redemptionPeriod: '1 Year', saleDates: 'August – October',
    overTheCounter: false,
    stateWebsite: 'http://www.in.gov/core/',
    stateStatutes: 'https://iga.in.gov/legislative/laws/2015/ic/',
    summary: 'Indiana tax liens carry a 1-year redemption period with penalty rates of 5% (redeemed ≤6 months) or 10% (redeemed >6 months). The lien holder must apply for a deed no later than 6 months after the 1-year redemption period expires, or the lien is forfeited.',
  },
  IA: {
    state: 'IA', stateName: 'Iowa',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '24% (2% per month)', bidMethod: 'Rotational / Random Selection',
    redemptionPeriod: '1 Year 9 Months', saleDates: '3rd Monday of June',
    overTheCounter: false,
    stateWebsite: 'https://www.iowa.gov/',
    stateStatutes: 'https://www.legis.iowa.gov/docs/iacode/2001/x.html',
    summary: 'Iowa tax liens earn 24% annually. Most counties use rotational or random-selection bidding rather than the statutory bid-down-ownership method. After 1 year 9 months, the lien holder must file a 90-day notice to terminate redemption rights. Failing to act within 3 years cancels the lien.',
  },
  KS: {
    state: 'KS', stateName: 'Kansas',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'August – October',
    overTheCounter: true,
    stateWebsite: 'http://www.kansas.gov/',
    stateStatutes: 'http://www.ksrevisor.org/statutes/ksa_ch79.html',
    summary: 'Kansas tax deed sales are conducted by the county sheriff. Some counties allow starting bids below the tax lien amount or set no minimum at all. Investors can purchase properties over the counter after failed auctions.',
  },
  KY: {
    state: 'KY', stateName: 'Kentucky',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '12%', bidMethod: 'Premium',
    redemptionPeriod: '1 Year', saleDates: 'April – May',
    overTheCounter: false,
    stateWebsite: 'http://www.kentucky.gov/',
    stateStatutes: 'http://www.lrc.ky.gov/statutes/index.aspx',
    summary: 'Kentucky tax liens earn 12% annually (1% per month). Investors must send notice to the property owner within 50 days of purchase. Tax deeds are obtained through judicial foreclosure after the 1-year redemption period.',
  },
  LA: {
    state: 'LA', stateName: 'Louisiana',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Redeemable Deed',
    interestRate: '12% APR + 5% Penalty', bidMethod: 'Bid Down Ownership',
    redemptionPeriod: '3 Years', saleDates: 'January – April',
    overTheCounter: false,
    stateWebsite: 'http://louisiana.gov/',
    stateStatutes: 'http://senate.legis.state.la.us/Documents/Constitution/Article7.htm#%C2%A725.%20Tax%20Sales',
    summary: "Louisiana's Napoleonic Code-based system sells redeemable deeds via bid-down-ownership. Investors earn 1%/month (12% annually) plus a 5% penalty upon redemption. Purchasers can request immediate writ of possession before the 3-year redemption expires.",
  },
  ME: {
    state: 'ME', stateName: 'Maine',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Year Round',
    overTheCounter: false,
    stateWebsite: 'http://www.maine.gov/portal/index.html',
    stateStatutes: 'https://mainelegislature.org/legis/statutes/36/title36ch105sec0.html',
    summary: 'Maine sells tax deeds via premium bid auction conducted by the municipal tax collector. No redemption period after sale.',
  },
  MD: {
    state: 'MD', stateName: 'Maryland',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '6% – 24% (varies by county)', bidMethod: 'Premium',
    redemptionPeriod: '6 Months (up to 2 years to foreclose)', saleDates: 'Year Round',
    overTheCounter: true,
    stateWebsite: 'http://www.maryland.gov/Pages/default.aspx',
    stateStatutes: 'http://law.justia.com/codes/maryland/2010/tax-property/title-14/subtitle-8/',
    summary: "Maryland's tax lien system is investor-friendly: the overbid premium is only due when filing for foreclosure (not at purchase). The lien can begin foreclosure 6 months after purchase, but must be filed within 2 years or the certificate becomes void.",
  },
  MA: {
    state: 'MA', stateName: 'Massachusetts',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Redeemable Deed',
    interestRate: '16%', bidMethod: 'Varies by County',
    redemptionPeriod: '6 Months', saleDates: 'Varies',
    overTheCounter: false,
    stateWebsite: 'http://www.mass.gov/portal/',
    stateStatutes: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleIX/Chapter60',
    summary: 'Massachusetts uses a "taking" process — tax collector records an Instrument of Taking or sells a Collector\'s Deed at auction. Interest accrues at 16% annually after taking. 6-month redemption period; judicial foreclosure terminates redemption rights.',
  },
  MI: {
    state: 'MI', stateName: 'Michigan',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'June – November',
    overTheCounter: true,
    stateWebsite: 'http://www.michigan.gov/',
    stateStatutes: 'http://www.legislature.mi.gov/(S(31thqnfiv3gn5gucwzcomuyp))/mileg.aspx?page=GetObject&objectname=mcl-chap211',
    summary: 'Michigan tax deed sales run June–November. Many counties use Title-Check LLC (tax-sale.info/ebayliveauctions.com). County forecloses in March–April, after which purchasing title from previous owners is no longer possible.',
  },
  MN: {
    state: 'MN', stateName: 'Minnesota',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Varies',
    overTheCounter: false,
    stateWebsite: 'https://mn.gov/portal/',
    stateStatutes: 'https://www.revisor.mn.gov/statutes/cite/282.01',
    summary: 'Minnesota delinquent taxes are "bid to the state" in May; if not redeemed, the property forfeits to the state and is sold at public auction to the highest bidder. County auditor manages the process.',
  },
  MS: {
    state: 'MS', stateName: 'Mississippi',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '18%', bidMethod: 'Premium (Overbid)',
    redemptionPeriod: '2 Years', saleDates: 'Last Monday of August',
    overTheCounter: true,
    stateWebsite: 'https://www.sos.ms.gov/',
    stateStatutes: null,
    summary: 'Mississippi uses an overbid competitive bid system. Interest is not earned on the overbid amount. Over-the-counter tax deed sales also available.',
  },
  MO: {
    state: 'MO', stateName: 'Missouri',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '10%', bidMethod: 'Premium',
    redemptionPeriod: '1 Year', saleDates: 'Year Round',
    overTheCounter: true,
    stateWebsite: 'http://www.mo.gov/',
    stateStatutes: 'http://www.moga.mo.gov/mostatutes/chapters/chapText140.html',
    summary: 'Missouri tax liens earn 10% annually. Investor must apply for a deed within 2 years of purchase or the lien ceases to be a lien. Non-residents must file a written jurisdiction agreement before bidding.',
  },
  MT: {
    state: 'MT', stateName: 'Montana',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '10%', bidMethod: 'Premium',
    redemptionPeriod: '2 – 3 Years', saleDates: 'July',
    overTheCounter: false,
    stateWebsite: 'http://mt.gov/',
    stateStatutes: 'http://leg.mt.gov/bills/mca_toc/15_17.htm',
    summary: 'Montana tax liens earn 10% annually. Investor must notify all interested parties within 60 days before and after redemption period expiration. Failure to notify results in the county treasurer canceling the lien.',
  },
  NE: {
    state: 'NE', stateName: 'Nebraska',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '14%', bidMethod: 'Round Robin (Rotational)',
    redemptionPeriod: '3 Years', saleDates: '1st Monday of March',
    overTheCounter: true,
    stateWebsite: 'http://www.nebraska.gov/',
    stateStatutes: 'http://nebraskalegislature.gov/laws/browse-chapters.php?chapter=77',
    summary: 'Nebraska uses a round-robin bidding system where each registered investor selects one parcel per round in sequence. Registration required with a non-refundable fee (~$25). 3-year redemption period at 14% annually.',
  },
  NV: {
    state: 'NV', stateName: 'Nevada',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Year Round',
    overTheCounter: false,
    stateWebsite: 'http://nv.gov/',
    stateStatutes: 'http://www.leg.state.nv.us/NRS/NRS-361.html',
    summary: 'Nevada is a pure tax deed state — no redemption period after purchase. Investor immediately owns the property outright. Deed is a quit claim deed, generally free and clear of most encumbrances except utility easements. Must be recorded within 30 days (NRS 361.590).',
  },
  NH: {
    state: 'NH', stateName: 'New Hampshire',
    investmentType: 'NOT_ACTIVE', investmentLabel: 'Not Currently Selling',
    interestRate: null, bidMethod: null,
    redemptionPeriod: null, saleDates: null,
    overTheCounter: false,
    stateWebsite: null, stateStatutes: null,
    summary: 'New Hampshire is not currently holding tax lien or tax deed sales.',
  },
  NJ: {
    state: 'NJ', stateName: 'New Jersey',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '18% + 4-6% Penalty', bidMethod: 'Bid Down Interest Rate',
    redemptionPeriod: '2 Years', saleDates: 'Varies by Municipality',
    overTheCounter: false,
    stateWebsite: 'http://www.state.nj.us/',
    stateStatutes: null,
    summary: 'All 566 New Jersey municipalities must hold at least one annual tax sale. Maximum rate is 18% plus a 4% penalty on liens ≤$5,000 or 6% on liens >$10,000. Investors bid down the interest rate; premium bids are also accepted at 0% interest.',
  },
  NM: {
    state: 'NM', stateName: 'New Mexico',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Year Round',
    overTheCounter: false,
    stateWebsite: 'http://www.newmexico.gov/',
    stateStatutes: 'http://law.justia.com/codes/new-mexico/2011/chapter7/article38/',
    summary: 'New Mexico handles tax sales at the state level via the State Property Tax Division (after 3 years of delinquency). Important: buyers take property subject to all outstanding prior interests and encumbrances of record.',
  },
  NY: {
    state: 'NY', stateName: 'New York',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Year Round',
    overTheCounter: true,
    stateWebsite: 'http://www.ny.gov/',
    stateStatutes: 'http://codes.findlaw.com/ny/real-property-tax-law/rpt-sect-1190.html',
    summary: 'New York City holds a separate annual tax lien sale (9-18% compounded daily). All other NY counties sell tax deeds via premium bid. FOIL (Freedom of Information Law) makes parcel maps and title history accessible. Real Property Transfer Report required with every deed.',
  },
  NC: {
    state: 'NC', stateName: 'North Carolina',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Year Round',
    overTheCounter: true,
    stateWebsite: 'http://www.ncgov.com/',
    stateStatutes: 'http://www.ncga.state.nc.us/EnactedLegislation/Statutes/HTML/ByArticle/Chapter_105/Article_26.html',
    summary: "North Carolina tax deeds are sold by premium bid. Upset bids allow any bidder to raise the winning bid by 5% (minimum $750) after the sale. Many counties use law firms (RBCWB or Kania Law) to conduct auctions.",
  },
  ND: {
    state: 'ND', stateName: 'North Dakota',
    investmentType: 'NOT_ACTIVE', investmentLabel: 'Not Currently Selling',
    interestRate: null, bidMethod: null,
    redemptionPeriod: null, saleDates: null,
    overTheCounter: false,
    stateWebsite: null, stateStatutes: null,
    summary: 'North Dakota is not currently holding tax lien or tax deed sales.',
  },
  OH: {
    state: 'OH', stateName: 'Ohio',
    investmentType: 'HYBRID', investmentLabel: 'Tax Lien + Tax Deed',
    interestRate: '18% (for tax lien counties)', bidMethod: 'Premium / Bid Down Interest',
    redemptionPeriod: '1 Year', saleDates: 'Year Round',
    overTheCounter: false,
    stateWebsite: 'http://www.ohio.gov/',
    stateStatutes: 'http://codes.ohio.gov/orc/5721',
    summary: 'Ohio is hybrid: counties with 200,000+ population may sell tax lien certificates (18%, 1-year redemption); smaller counties sell tax deeds via sheriff sales. Franklin (Columbus), Cuyahoga (Cleveland), and Hamilton (Cincinnati) counties hold lien auctions.',
  },
  OK: {
    state: 'OK', stateName: 'Oklahoma',
    investmentType: 'HYBRID', investmentLabel: 'Tax Lien + Tax Deed',
    interestRate: '8%', bidMethod: 'Random Selection',
    redemptionPeriod: '2 Years', saleDates: 'October (Tax Sale) · June (Resale)',
    overTheCounter: true,
    stateWebsite: 'https://www.ok.gov/',
    stateStatutes: 'http://www.oscn.net/applications/OCISWeb/index.asp?level=1&ftdb=STOKST68#Article31-CollectionofDelinquentTaxes',
    summary: 'Oklahoma has three sequential opportunities: Tax Sale (first Monday October, 8% lien, 2-year redemption), Resale (second Monday June, deeds for unredeemed properties), and County Commissioner Sale (properties unsold at prior two sales). Low competition due to modest 8% return.',
  },
  OR: {
    state: 'OR', stateName: 'Oregon',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium by Lottery',
    redemptionPeriod: 'Varies by County', saleDates: 'Year Round',
    overTheCounter: true,
    stateWebsite: 'http://oregon.gov/',
    stateStatutes: 'http://www.oregonlaws.org/ors/volume/3',
    summary: 'Oregon uses a lottery-based premium bid system. The state has strong GIS resources. Statutes include provisions for financing purchasers — unique among tax deed states.',
  },
  PA: {
    state: 'PA', stateName: 'Pennsylvania',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Varies by County',
    overTheCounter: true,
    stateWebsite: 'http://www.pa.gov/',
    stateStatutes: 'http://www.legis.state.pa.us/cfdocs/legis/CH/PUBLIC/cons_view_affecting.cfm?ttl_id=72',
    summary: "Pennsylvania's Tax Claim Bureau holds Upset Sales (September), then Judicial Sales (liens cleared), then Repository Sales for unsold properties. Repository properties can be purchased year-round via mail-in offer. Special rules apply in Philadelphia, Pittsburgh, Scranton, and Allegheny County.",
  },
  RI: {
    state: 'RI', stateName: 'Rhode Island',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Redeemable Deed',
    interestRate: '1% per Month + 10% Penalty', bidMethod: 'Premium',
    redemptionPeriod: '1 Year', saleDates: 'Year Round',
    overTheCounter: false,
    stateWebsite: 'https://www.ri.gov/',
    stateStatutes: 'http://webserver.rilin.state.ri.us/Statutes/TITLE44/44-9/INDEX.HTM',
    summary: 'Rhode Island sells hybrid tax deeds with a 1-year redemption period. 10% penalty if redeemed within 6 months; 1% additional penalty per month after that. Premium bid, highest bidder wins.',
  },
  SC: {
    state: 'SC', stateName: 'South Carolina',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Redeemable Deed',
    interestRate: '3% – 12% (tiered by quarter)', bidMethod: 'Premium',
    redemptionPeriod: '12 Months', saleDates: 'Fall',
    overTheCounter: false,
    stateWebsite: 'http://www.sc.gov/',
    stateStatutes: 'http://www.scstatehouse.gov/code/title12.php',
    summary: 'South Carolina uses tiered interest: 3% (months 1-3), 6% (months 4-6), 9% (months 7-9), 12% (months 10-12). Opening bid includes all delinquent taxes and current year taxes. If not redeemed after 12 months, investor receives a non-warranty tax deed.',
  },
  SD: {
    state: 'SD', stateName: 'South Dakota',
    investmentType: 'NOT_ACTIVE', investmentLabel: 'Not Currently Selling',
    interestRate: null, bidMethod: null,
    redemptionPeriod: null, saleDates: null,
    overTheCounter: false,
    stateWebsite: null, stateStatutes: null,
    summary: 'South Dakota is not currently holding tax lien or tax deed sales.',
  },
  TN: {
    state: 'TN', stateName: 'Tennessee',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Redeemable Deed',
    interestRate: '12% Simple', bidMethod: 'Premium',
    redemptionPeriod: '1 Year', saleDates: 'Varies by County',
    overTheCounter: true,
    stateWebsite: 'http://www.tennessee.gov/',
    stateStatutes: 'http://law.justia.com/codes/tennessee/2010/title-67',
    summary: 'Tennessee redeemable deed state with 1-year redemption at 12% simple interest (applied to overbid amount as well). Investor can apply for an immediate writ of possession and collect rent during the redemption period — a significant income opportunity.',
  },
  TX: {
    state: 'TX', stateName: 'Texas',
    investmentType: 'REDEEMABLE_DEED', investmentLabel: 'Redeemable Deed',
    interestRate: '25% Penalty per Year', bidMethod: 'Premium',
    redemptionPeriod: '6 – 18 Months', saleDates: '1st Tuesday of Each Month',
    overTheCounter: true,
    stateWebsite: 'http://www.texas.gov/',
    stateStatutes: 'https://statutes.capitol.texas.gov/Docs/TX/htm/TX.32.htm',
    summary: 'Texas offers one of the highest penalty rates in the nation: 25% per year (50% total over 2 years). Monthly sales are held the first Tuesday of each month. Many counties use law firms (Perdue Brandon, Linebarger Goggan, McCreary Veselka, etc.) to handle sales.',
  },
  UT: {
    state: 'UT', stateName: 'Utah',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'May',
    overTheCounter: true,
    stateWebsite: 'http://www.utah.gov/index.html',
    stateStatutes: 'https://le.utah.gov/xcode/Title59/Chapter2/59-2-P13.html',
    summary: 'All Utah counties hold tax deed sales on the same day in May. Oral bid, premium method. Payment must be by cash or certified funds. Property has been delinquent 5 years before eligible for sale. Investor can designate a proxy bidder via notarized statement.',
  },
  VT: {
    state: 'VT', stateName: 'Vermont',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '12%', bidMethod: 'Premium',
    redemptionPeriod: '2 Years', saleDates: 'Varies by County',
    overTheCounter: false,
    stateWebsite: 'http://www.vermont.gov/portal/',
    stateStatutes: 'http://legislature.vermont.gov/statutes/chapter/32/133',
    summary: 'Vermont tax lien certificates earn 12% annually (or a 12% penalty upon redemption depending on timing). 2-year redemption period. The tax lien remains valid for up to 15 years.',
  },
  VA: {
    state: 'VA', stateName: 'Virginia',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Varies by County',
    overTheCounter: false,
    stateWebsite: 'https://www.virginia.gov/',
    stateStatutes: 'http://law.lis.virginia.gov/vacodefull/title58.1/chapter32/article11/',
    summary: 'Virginia county treasurers initiate foreclosure on December 31 for properties 2+ years delinquent. Certified notices sent to owners, followed by newspaper publication ~3 weeks before sale. Deed issued to highest bidder; delivered by mail ~1 month after auction.',
  },
  WA: {
    state: 'WA', stateName: 'Washington',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Fall / Winter',
    overTheCounter: true,
    stateWebsite: 'http://access.wa.gov/',
    stateStatutes: 'http://apps.leg.wa.gov/rcw/default.aspx?Cite=84',
    summary: "Washington foreclosures are filed by county treasurers once taxes are 3 years unpaid. Properties sold 'as-is' at annual foreclosure auctions (King County: September). Buyers often need a quiet title action for clear ownership. Real Estate Excise Tax (REET) may attach as a lien if unpaid by seller.",
  },
  WV: {
    state: 'WV', stateName: 'West Virginia',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '12%', bidMethod: 'Premium',
    redemptionPeriod: '18 Months', saleDates: 'July – September',
    overTheCounter: true,
    stateWebsite: 'http://www.wv.gov/Pages/default.aspx#home',
    stateStatutes: 'http://www.legis.state.wv.us/WVCODE/Code.cfm?chap=11a&art=1',
    summary: "West Virginia sheriff conducts all delinquent property auctions. Tax lien certificates earn 12% annually. All liens sold to the highest bidder — no interest earned on any overbid amount. Over-the-counter sales available after failed auctions.",
  },
  WI: {
    state: 'WI', stateName: 'Wisconsin',
    investmentType: 'TAX_DEED', investmentLabel: 'Tax Deed',
    interestRate: null, bidMethod: 'Premium',
    redemptionPeriod: null, saleDates: 'Year Round',
    overTheCounter: true,
    stateWebsite: 'http://www.wisconsin.gov/Pages/home.aspx',
    stateStatutes: 'http://docs.legis.wisconsin.gov/statutes/statutes/75/521',
    summary: 'Wisconsin counties hold tax liens for 2 years; if unredeemed by August 31 of the second year, the county forecloses and holds a tax deed sale. List published in local newspaper 6 weeks prior. Some counties accept sealed bids submitted the day before.',
  },
  WY: {
    state: 'WY', stateName: 'Wyoming',
    investmentType: 'TAX_LIEN', investmentLabel: 'Tax Lien',
    interestRate: '15% APR + 3% Penalty (year 1)', bidMethod: 'Random Selection',
    redemptionPeriod: '4 Years', saleDates: 'Summer',
    overTheCounter: false,
    stateWebsite: 'http://wyoming.gov/',
    stateStatutes: 'http://legisweb.state.wy.us/LSOWEB/SearchResults.aspx?cx=017715011151602216554:5hjhyhx9vlm&cof=FORID%3A11&ie=UTF-8&q=Title+39%2C+CH+13&sa=Search',
    summary: 'Wyoming has a 4-year redemption period at 15% annually plus a 3% first-year penalty. Lower competition due to smaller population. Lien holder must file for deed within 6 years of purchase, and must satisfy all other lien holders if multiple lien holders exist on the same property.',
  },
}

export function getStateInfo(stateCode: string): StateInfo | null {
  return STATE_INFO[stateCode.toUpperCase()] ?? null
}

/** Badge color based on investment category */
export function investmentTypeBadgeClass(type: InvestmentCategory): string {
  switch (type) {
    case 'TAX_LIEN':       return 'bg-blue-100 text-blue-800'
    case 'TAX_DEED':       return 'bg-purple-100 text-purple-800'
    case 'REDEEMABLE_DEED': return 'bg-amber-100 text-amber-800'
    case 'HYBRID':         return 'bg-teal-100 text-teal-800'
    case 'NOT_ACTIVE':     return 'bg-zinc-100 text-zinc-500'
    default:               return 'bg-zinc-100 text-zinc-500'
  }
}
